# -*- coding: utf-8 -*-
"""Inspecting_grayscale_images.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/PacktPublishing/Modern-Computer-Vision-with-PyTorch-2E/blob/main/Chapter03/Inspecting_grayscale_images.ipynb

<a href="https://colab.research.google.com/github/PacktPublishing/Modern-Computer-Vision-with-PyTorch-2E/blob/main/Chapter03/Inspecting_grayscale_images.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
"""

#!wget -q https://www.dropbox.com/s/lpw10qawsc5ipbn/MyImage.JPG -O MyImage.jpg

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import cv2, matplotlib.pyplot as plt

img = cv2.imread("MyImage.jpg")

img = img[50:250, 40:240]
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
plt.imshow(img_gray, cmap="gray")

img_gray_small = cv2.resize(img_gray, (25, 25))
plt.imshow(img_gray_small, cmap="gray")

print(img_gray_small)

