# -*- coding: utf-8 -*-
"""Numpy_Vs_Torch_object_computation_speed_comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/PacktPublishing/Modern-Computer-Vision-with-PyTorch-2E/blob/main/Chapter02/Numpy_Vs_Torch_object_computation_speed_comparison.ipynb
"""

import torch
x = torch.rand(1, 6400)
y = torch.rand(6400, 5000)

device = 'cuda' if torch.cuda.is_available() else 'cpu'
assert device == 'cuda', "This exercise assumes the notebook is on a GPU machine"

x, y = x.to(device), y.to(device)

# Commented out IPython magic to ensure Python compatibility.
# %timeit z=(x@y)

# Commented out IPython magic to ensure Python compatibility.
x, y = x.cpu(), y.cpu()
# %timeit z=(x@y)

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
x = np.random.random((1, 6400))
y = np.random.random((6400, 5000))
# %timeit z = np.matmul(x,y)

l